# Generated by Django 3.2.7 on 2021-10-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='expare_date',
            field=models.DateTimeField(null=True),
        ),
    ]
