# Generated by Django 3.2.7 on 2021-09-30 13:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listmodel',
            options={'verbose_name': 'Список дел', 'verbose_name_plural': 'Список дел'},
        ),
        migrations.AlterUniqueTogether(
            name='listmodel',
            unique_together={('name', 'user')},
        ),
    ]
